# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "demo tasks illustrating various capabilities of MTC."
AUTHOR = "Robert Haschke <rhaschke@techfak.uni-bielefeld.de>"
ROS_AUTHOR = "Robert Haschke <rhaschke@techfak.uni-bielefeld.de>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "moveit_task_constructor"
ROS_BPN = "moveit_task_constructor_demo"

ROS_BUILD_DEPENDS = " \
    moveit-core \
    moveit-ros-planning-interface \
    moveit-task-constructor-core \
    swri-roscpp \
    generate-parameter-library \
    moveit-configs-utils \
    moveit-resources-panda-moveit-config \
    moveit-task-constructor-capabilities \
    py-binding-tools \
    yaml-cpp-vendor \
    generate-parameter-library-py \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    libyaml-vendor-native \
    generate-parameter-library-py-native \
"

ROS_EXPORT_DEPENDS = " \
    moveit-core \
    moveit-ros-planning-interface \
    moveit-task-constructor-core \
    swri-roscpp \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    moveit-core \
    moveit-resources-panda-moveit-config \
    moveit-ros-planning-interface \
    moveit-task-constructor-capabilities \
    moveit-task-constructor-core \
    swri-roscpp \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros-gbp/moveit_task_constructor-release/archive/release/noetic/moveit_task_constructor_demo/0.1.3-1.tar.gz
ROS_BRANCH ?= "branch=master"
SRC_URI = "git://github.com/Nettoysfkf/moveit-task-constructor-demo;${ROS_BRANCH};protocol=https"
SRCREV = "40ded5a72d5fc48333a9c19547173f2a60fcea47"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
