# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated
inherit cmake_qt5

DESCRIPTION = "MoveGroupCapabilites to interact with MoveIt"
AUTHOR = "Michael v4hn Goerner <me@v4hn.de>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=11;endline=11;md5=68b329da9893e34099c7d8ad5cb9c940"

ROS_CN = "moveit_task_constructor"
ROS_BPN = "moveit_task_constructor_capabilities"

ROS_BUILD_DEPENDS = " \
    control-msgs interactive-markers moveit-core moveit-ros-perception moveit-ros-planning-interface moveit-servo moveit-hybrid-planning moveit-visual-tools \
    moveit-msgs pluginlib rviz-visual-tools tf2-eigen tf2-geometry-msgs tf2-ros moveit-task-constructor-core libeigen geometric-shapes moveit-common \
    moveit-ros-planning controller-manager gripper-controllers qtbase \
    \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = " \
    controller-manager gripper-controllers joint-state-broadcaster joint-state-publisher joint-trajectory-controller joy moveit moveit-resources-panda-moveit-config \
    moveit-configs-utils robot-state-publisher ros2-control rviz2 xacro \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    ament-cmake-gtest \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros-gbp/moveit_task_constructor-release/archive/release/noetic/moveit_task_constructor_capabilities/0.1.3-1.tar.gz
ROS_BRANCH ?= "branch=master"
SRC_URI = "git://github.com/Nettoysfkf/moveit2_tutorials;${ROS_BRANCH};protocol=https"
SRCREV = "b8f954ce045b00f29de4da24146eb7732e7b2a9e"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
