# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "Messages for MoveIt Task Pipeline"
AUTHOR = "Robert Haschke <rhaschke@techfak.uni-bielefeld.de>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=6;endline=6;md5=75730354549103aaba72b66caf53717b"

ROS_CN = "moveit_task_constructor"
ROS_BPN = "moveit_task_constructor_msgs"

ROS_BUILD_DEPENDS = " \
    moveit-msgs \
    visualization-msgs \
    rosidl-default-generators \
    rosidl-adapter \
    ament-cmake-ros \
    ament-cmake-gmock \
    ament-cmake-gtest \
    ament-cmake-pytest \
    python3-numpy \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    rosidl-adapter-native \
    python3-numpy-native \
    rosidl-default-generators-native \
"

ROS_EXPORT_DEPENDS = " \
    moveit-msgs \
    visualization-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    moveit-msgs \
    visualization-msgs \
    rosidl-default-runtime \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros-gbp/moveit_task_constructor-release/archive/release/noetic/moveit_task_constructor_msgs/0.1.3-1.tar.gz
ROS_BRANCH ?= "branch=master"
SRC_URI = "git://github.com/Nettoysfkf/moveit-task-constructor-msgs;${ROS_BRANCH};protocol=https"
SRCREV = "b80ed10acd7a429c7a1e710d0d0ad52660e47d6a"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
