# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "Tools for marker creation / handling"
AUTHOR = "Robert Haschke <rhaschke@techfak.uni-bielefeld.de>"
ROS_AUTHOR = "Robert Haschke <rhaschke@techfak.uni-bielefeld.de>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=6;endline=6;md5=75730354549103aaba72b66caf53717b"

ROS_CN = "moveit_task_constructor"
ROS_BPN = "rviz_marker_tools"

ROS_BUILD_DEPENDS = " \
    geometry-msgs \
    swri-roscpp \
    tf2-eigen \
    urdfdom-headers \
    urdfdom \
    moveit-common \
    visualization-msgs \
    rviz2 \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    eigen3-cmake-module-native \
    libeigen-native \
"

ROS_EXPORT_DEPENDS = " \
    geometry-msgs \
    swri-roscpp \
    rviz2 \
    tf2-eigen \
    visualization-msgs \
    libeigen \
    eigen3-cmake-module \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    geometry-msgs \
    swri-roscpp \
    rviz2 \
    tf2-eigen \
    visualization-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros-gbp/moveit_task_constructor-release/archive/release/noetic/rviz_marker_tools/0.1.3-1.tar.gz
ROS_BRANCH ?= "branch=master"
SRC_URI = "git://github.com/Nettoysfkf/rviz_marker_tools;${ROS_BRANCH};protocol=https"
SRCREV = "aacd2ab69ccf8eb62b1c6ddcf53fc286c9928b29"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
